site_name: Rankify Documentation
site_url: https://github.com/DataScienceUIBK/Rankify
theme:
  name: material
markdown_extensions:
  - toc:
      permalink: true
      separator: "_"
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: false  # This prevents module names from being added separately
            show_source: false
            heading_level: 2  # Ensure consistent heading levels
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Usage: usage.md
  - Reference:
      - Dataset: api/dataset.md
      - Metrics: api/metrics.md
      - Retrievers:
          - Retriever: api/retrievers/retriever.md
          - BM25 Retriever: api/retrievers/bm25.md
          - Dense Retriever: api/retrievers/dense.md
          - BGE Retriever: api/retrievers/bge.md
          - Colbert Retriever: api/retrievers/colbert.md
          - Contriever Retriever: api/retrievers/contriever.md
      - Rerankers:
          - Base: api/rerankings/base.md
          - Reranking: api/rerankings/reranking.md
          - UPR: api/rerankings/upr.md
          - FlashRank: api/rerankings/flashrank.md
          - RankGPT: api/rerankings/rankgpt.md
          - Blender Reranker: api/rerankings/blender.md
          - ColBERT Reranker: api/rerankings/colbert_ranker.md
          - EchoRank: api/rerankings/echo_rank.md
          - First Reranker: api/rerankings/first_ranker.md
          - Incontext Reranker: api/rerankings/incontext_reranker.md
          - InRank Reranker: api/rerankings/inrank.md
          - Listt5 Reranker: api/rerankings/listt5.md
          - Lit5 Reranker: api/rerankings/lit5.md
          - LLM Layerwise Reranker: api/rerankings/llm_layerwise_ranker.md
          - LLM2vec Reranker: api/rerankings/llm2vec_reranker.md
          - Monobert Reranker: api/rerankings/monobert.md
          - Monot5 Reranker: api/rerankings/monot5.md
          - Rank Fid Reranker: api/rerankings/rank_fid.md
          - Rankt5 Reranker: api/rerankings/rankt5.md
          - Sentence Transformer Reranker: api/rerankings/sentence_transformer_reranker.md
          - splade Reranker: api/rerankings/splade_reranker.md
          - Transformer Reranker: api/rerankings/transformer_reranker.md
          - twolar Reranker: api/rerankings/twolar.md
          - Vicuna Reranker: api/rerankings/vicuna_reranker.md
          - Zephyr Reranker: api/rerankings/zephyr_reranker.md
      - Generators:
          - Overview: api/generators/index.md
          - T5 Generator: api/generators/t5_generator.md
          - GPT Generator: api/generators/gpt_generator.md
  - License: license.md
