site_name: Rankify Documentation
site_url: https://github.com/DataScienceUIBK/Rankify
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Installation: installation.md
  - Usage: usage.md
  - Reference:
      - Dataset: api/dataset.md
      - Generator: api/generator.md
      - Metrics: api/metrics.md
      - Retrievers: api/retrievers.md
      - Utils: api/utils.md
  - License: license.md
